#!/bin/bash

if [ $# != 4 ]; then
   echo "Usage: add-private-host [hostname] [path] [category] [label]"
   exit 1
fi

ISHOST=`grep $1 /etc/hosts`

if [ "$ISHOST" == "" ]; then
    echo "{{ gateway_ip }} $1" >> /etc/hosts
    redis-cli SET $1 $2
fi

ISMEMBER=`redis-cli -n 1 LRANGE "$3" 0 -1 | grep $1`

if [ "$ISMEMBER" == "" ]; then
    echo "Adding $1 to $3"
    redis-cli -n 1 LPUSH "$3" "$4, $1"
else
    echo "$1 already a member of $3"
fi

